CREATE TABLE "starter_default_settings_limits" (
	"id" serial PRIMARY KEY NOT NULL,
	"pr_flt_en_min" integer DEFAULT 0,
	"pr_flt_en_max" integer DEFAULT 65355,
	"flc_min" real DEFAULT 1,
	"flc_max" real DEFAULT 10,
	"as_dly_min" integer DEFAULT 5,
	"as_dly_max" integer,
	"tpf_min" real DEFAULT 0,
	"tpf_max" real DEFAULT 10,
	"v_en" integer DEFAULT 0,
	"c_en" integer DEFAULT 0,
	"ipf_min" real DEFAULT 0,
	"ipf_max" real DEFAULT 300,
	"lvf_min" real DEFAULT 300,
	"lvf_max" real DEFAULT 380,
	"hvf_min" real DEFAULT 480,
	"hvf_max" real DEFAULT 550,
	"vif_min" real DEFAULT 5,
	"vif_max" real DEFAULT 30,
	"paminf_min" real DEFAULT 100,
	"paminf_max" real DEFAULT 110,
	"pamaxf_min" real DEFAULT 125,
	"pamaxf_max" real DEFAULT 130,
	"f_dr_min" real DEFAULT 10,
	"f_dr_max" real DEFAULT 50,
	"f_ol_min" real DEFAULT 120,
	"f_ol_max" real DEFAULT 150,
	"f_lr_min" real DEFAULT 350,
	"f_lr_max" real DEFAULT 450,
	"f_opf" real DEFAULT 0.5,
	"f_ci_min" real DEFAULT 15,
	"f_ci_max" real DEFAULT 35,
	"pfa_min" real DEFAULT 280,
	"pfa_max" real DEFAULT 360,
	"lva_min" real DEFAULT 340,
	"lva_max" real DEFAULT 380,
	"hva_min" real DEFAULT 470,
	"hva_max" real DEFAULT 500,
	"via_min" real DEFAULT 10,
	"via_max" real DEFAULT 20,
	"pamina_min" real DEFAULT 100,
	"pamina_max" real DEFAULT 115,
	"pamaxa_min" real DEFAULT 125,
	"pamaxa_max" real DEFAULT 135,
	"dr_min" real DEFAULT 10,
	"dr_max" real DEFAULT 60,
	"ol_min" real DEFAULT 110,
	"ol_max" real DEFAULT 150,
	"lr_min" real DEFAULT 300,
	"lr_max" real DEFAULT 400,
	"ci_min" real DEFAULT 15,
	"ci_max" real DEFAULT 30,
	"lvr_min" real DEFAULT 360,
	"lvr_max" real DEFAULT 400,
	"hvr_min" real DEFAULT 450,
	"hvr_max" real DEFAULT 470,
	"olf_min" real DEFAULT 1,
	"olf_max" real DEFAULT 9,
	"lrf_min" real DEFAULT 1,
	"lrf_max" real DEFAULT 9,
	"opf_min" real DEFAULT 0.5,
	"opf_max" real DEFAULT 1,
	"cif_min" real DEFAULT 0.5,
	"cif_max" real DEFAULT 1,
	"drf_min" real DEFAULT 5,
	"drf_max" real DEFAULT 20,
	"irr_min" real DEFAULT 10,
	"irr_max" real DEFAULT 50,
	"olr_min" real DEFAULT 10,
	"olr_max" real DEFAULT 50,
	"cir_min" real DEFAULT 10,
	"cir_max" real DEFAULT 50,
	"ug_r_min" real DEFAULT 1,
	"ug_r_max" real DEFAULT 65536,
	"ug_y_min" real DEFAULT 1,
	"ug_y_max" real DEFAULT 65536,
	"ug_b_min" real DEFAULT 1,
	"ug_b_max" real DEFAULT 65536,
	"ip_r_min" real DEFAULT 1,
	"ip_r_max" real DEFAULT 65536,
	"ip_y_min" real DEFAULT 1,
	"ip_y_max" real DEFAULT 65536,
	"ip_b_min" real DEFAULT 1,
	"ip_b_max" real DEFAULT 65536,
	"vg_r_min" real DEFAULT 0,
	"vg_r_max" real DEFAULT 0,
	"vg_y_min" real DEFAULT 0,
	"vg_y_max" real DEFAULT 0,
	"vg_b_min" real DEFAULT 0,
	"vg_b_max" real DEFAULT 0,
	"vo_r_min" real DEFAULT 0,
	"vo_r_max" real DEFAULT 0,
	"vo_y_min" real DEFAULT 0,
	"vo_y_max" real DEFAULT 0,
	"vo_b_min" real DEFAULT 0,
	"vo_b_max" real DEFAULT 0,
	"ig_r_min" real DEFAULT 1,
	"ig_r_max" real DEFAULT 65536,
	"ig_y_min" real DEFAULT 1,
	"ig_y_max" real DEFAULT 65536,
	"ig_b_min" real DEFAULT 1,
	"ig_b_max" real DEFAULT 65536,
	"io_r_min" real DEFAULT 0,
	"io_r_max" real DEFAULT 0,
	"io_y_min" real DEFAULT 0,
	"io_y_max" real DEFAULT 0,
	"io_b_min" real DEFAULT 0,
	"io_b_max" real DEFAULT 0,
	"r1" integer DEFAULT 0,
	"r2" integer DEFAULT 0,
	"off" integer DEFAULT 0,
	"ca_fn" varchar(100),
	"bkr_adrs" varchar(100),
	"sn" varchar(50),
	"usrn" varchar(50),
	"pswd" varchar(50),
	"prd_url" varchar(100),
	"port" integer DEFAULT 1883,
	"crt_en" integer DEFAULT 2048,
	"sms_pswd" varchar(20),
	"c_lang" integer DEFAULT 1,
	"auth_num" varchar(15)[],
	"dft_liv_f" integer DEFAULT 5,
	"h_liv_f" integer DEFAULT 2,
	"m_liv_f" integer DEFAULT 4,
	"l_liv_f" integer DEFAULT 3,
	"pwr_info_f" integer DEFAULT 20,
	"ivrs_en" integer DEFAULT 0,
	"sms_en" integer DEFAULT 0,
	"rmt_en" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
ALTER TABLE "user_activity_logs" ALTER COLUMN "old_data" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "user_activity_logs" ALTER COLUMN "new_data" SET DATA TYPE varchar;--> statement-breakpoint
-- ALTER TABLE "user_activity_logs" ADD COLUMN "field_name" varchar;