CREATE TYPE "public"."acknowledgement_enum" AS ENUM('TRUE', 'FALSE');--> statement-breakpoint
CREATE TABLE "starter_settings" (
	"id" serial PRIMARY KEY NOT NULL,
	"dvc_flt_en" integer DEFAULT 0,
	"dvc_flc" real,
	"dvc_st" integer,
	"starter_id" integer NOT NULL,
	"pcb_number" varchar NOT NULL,
	"dvc_flt_ipf" real,
	"dvc_flt_lvf" real,
	"dvc_flt_hvf" real,
	"dvc_flt_vif" real,
	"dvc_flt_paminf" real,
	"dvc_flt_pamaxf" real,
	"dvc_alt_pfa" real,
	"dvc_alt_lva" real,
	"dvc_alt_hva" real,
	"dvc_alt_via" real,
	"dvc_alt_pamina" real,
	"dvc_alt_pamaxa" real,
	"dvc_rec_lvr" real,
	"dvc_rec_hvr" real,
	"mtr_flt_dr" real,
	"mtr_flt_ol" real,
	"mtr_flt_lr" real,
	"mtr_flt_opf" real,
	"mtr_flt_ci" real,
	"mtr_alt_dr" real,
	"mtr_alt_ol" real,
	"mtr_alt_lr" real,
	"mtr_alt_ci" real,
	"mtr_rec_ol" real,
	"mtr_rec_lr" real,
	"mtr_rec_ci" real,
	"atml_ug_r" integer,
	"atml_ug_y" integer,
	"atml_ug_b" integer,
	"atml_ig_r" integer,
	"atml_ig_y" integer,
	"atml_ig_b" integer,
	"mqt_ca_fn" varchar,
	"mqt_bkr_adrs" varchar,
	"mqt_c_id" varchar,
	"mqt_emqx_usrn" varchar,
	"mqt_emqx_pswd" varchar,
	"mqt_prod_http" varchar,
	"mqt_bkp_http" varchar,
	"mqt_bkr_port" integer,
	"mqt_ce_len" integer,
	"ivrs_sms_pswd" varchar,
	"ivrs_c_lang" integer,
	"ivrs_auth_num" json,
	"frq_dft_liv_f" integer,
	"frq_h_liv_f" integer,
	"frq_m_liv_f" integer,
	"frq_l_liv_f" integer,
	"frq_pwr_info_f" integer,
	"feats_ivrs_en" integer DEFAULT 0,
	"feats_sms_en" integer DEFAULT 1,
	"feats_rmt_en" integer DEFAULT 0,
	"flt_en_ipf" integer DEFAULT 1,
	"flt_en_lvf" integer DEFAULT 1,
	"flt_en_hvf" integer DEFAULT 1,
	"flt_en_vif" integer DEFAULT 1,
	"flt_en_dr" integer DEFAULT 1,
	"flt_en_ol" integer DEFAULT 1,
	"flt_en_lr" integer DEFAULT 1,
	"flt_en_opf" integer DEFAULT 1,
	"flt_en_ci" integer DEFAULT 1,
	"time_stamp" timestamp DEFAULT now(),
	"is_new_configuration_saved" integer DEFAULT 1,
	"acknowledgement" "acknowledgement_enum" DEFAULT 'FALSE',
	"created_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
ALTER TABLE "starter_settings" ADD CONSTRAINT "starter_settings_starter_id_starter_boxes_id_fk" FOREIGN KEY ("starter_id") REFERENCES "public"."starter_boxes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "starter_settings" ADD CONSTRAINT "starter_settings_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "starter_settings_idx" ON "starter_settings" USING btree ("starter_id");