ALTER TABLE "starter_default_settings_limits" ALTER COLUMN "ca_fn" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_default_settings_limits" ALTER COLUMN "bkr_adrs" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_default_settings_limits" ALTER COLUMN "sn" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_default_settings_limits" ALTER COLUMN "usrn" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_default_settings_limits" ALTER COLUMN "pswd" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_default_settings_limits" ALTER COLUMN "prd_url" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_default_settings_limits" ALTER COLUMN "sms_pswd" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_default_settings" ALTER COLUMN "ca_fn" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_default_settings" ALTER COLUMN "bkr_adrs" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_default_settings" ALTER COLUMN "sn" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_default_settings" ALTER COLUMN "usrn" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_default_settings" ALTER COLUMN "pswd" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_default_settings" ALTER COLUMN "prd_url" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_default_settings" ALTER COLUMN "sms_pswd" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings_limits" ALTER COLUMN "ca_fn" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings_limits" ALTER COLUMN "bkr_adrs" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings_limits" ALTER COLUMN "sn" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings_limits" ALTER COLUMN "usrn" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings_limits" ALTER COLUMN "pswd" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings_limits" ALTER COLUMN "prd_url" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings_limits" ALTER COLUMN "sms_pswd" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings" ALTER COLUMN "ca_fn" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings" ALTER COLUMN "bkr_adrs" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings" ALTER COLUMN "sn" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings" ALTER COLUMN "usrn" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings" ALTER COLUMN "pswd" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings" ALTER COLUMN "prd_url" SET DEFAULT 'NULL';--> statement-breakpoint
ALTER TABLE "starter_settings" ALTER COLUMN "sms_pswd" SET DEFAULT 'NULL';